name: Test
on: [push, pull_request]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache Node dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Amplify
        run: npm install -g @aws-amplify/cli

      - name: Install dependencies
        run: npm install

      - name: Test the application
        run: npm test
